config/routes.rb
Rails.application.routes.draw do

  root :to => 'tops#about'

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'publics/sessions',
    passwords: 'publics/passwords',
    registrations: 'publics/registrations'
  }

  namespace :admins do
    # 管理者(ユーザー機能)
    resources :users, only: [:index, :show, :destroy]
    # 管理者(問い合わせ機能)
    resources :inquiries, only: [:index, :show]
    # 管理者(問い合わせ返信機能)
    resources :inquiry_replies, only: [:edit, :update]
    # 管理者(ゲームジャンル追加、削除機能)
    resources :gamegenres, only: [:new, :create, :destroy]
    # 管理者(通報機能)
    resources :reports, only: [:index]
  end

  scope module: :publics do
    # 問い合わせ
    resources :inquiries, only: [:create, :new]
    # DM機能(メッセージ)
    resources :messages, only: [:create, :index]
    # DM機能(ルーム)
    resources :rooms, only: [:index, :create, :show]
    # 投稿機能
    resources :posts, only: [:index, :create, :new, :show, :destroy]
    # 通報機能
    resources :reports, only: [:create, :new]
    # カレンダー
    resources :events, only: [:create, :new, :index]
    # マッチング機能
    resources :relationships, only: [:create, :update]
    # ユーザー機能
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    get 'users/:id/matchings' => 'users#matching', as: 'matching'
    get 'users/:id/matchings/info' => 'users#info', as: 'info'
    get 'users/:id/edit2' => 'users#edit2', as: 'edit2'
  end

  get 'term' => 'tops#term'
  get 'privacy_policy' => 'tops#privacy_policy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  # マッチング機能
  # following_id => フォローされているユーザーid、 follower_id => フォローしているユーザーid
  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :following_relationships, source: :following
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Relationship', dependent: :destroy
  has_many :followed, through: :follower_relationships, source: :follower
  # 投稿機能
  has_many :posts, dependent: :destroy
  # 問い合わせ機能
  has_many :inquiries, dependent: :destroy
  # 通報機能
  has_many :reports, dependent: :destroy
  # DM機能(エントリー)
  has_many :entries, dependent: :destroy
  # DM機能(メッセージ)
  has_many :messages, dependent: :destroy
  # 好きなゲーム種類
  has_many :likes, dependent: :destroy
  has_many :gamegenres, through: :likes
  # カレンダー機能
  has_many :events, dependent: :destroy

  mount_uploader :image_profile_id, ImageUploader

  enum active_content: { 全力: true, 楽しむ: false }
  enum prefecture: {
        北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
        茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
        新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
        岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
        滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
        鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
        徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
        福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47
  }

  validates :first_name, presence: true, length: { maximum: 10 }
  validates :last_name, presence: true, length: { maximum: 10 }
  validates :first_name_kana, presence: true, length: { maximum: 10 }
  validates :last_name_kana, presence: true, length: { maximum: 10 }
  validates :nickname, presence: true, length: { maximum: 6 }, uniqueness: true
  validates :birthday, presence: true

  def follow(other_user)
    unless self == other_user
      following_relationships.find_or_create_by(following_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = following_relationships.find_by(following_id: other_user.id)
    relationship.destroy if relationship
  end

  # :自分がフォローしている人のデータを取得(other_user : 自分がフォローしたユーザー):
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  # :自分をフォローした人のデータを取得(other_user : 自分をフォローしたユーザー):
  def followed?(other_user)
    follower_relationships.find_by(follower_id: other_user.id)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::ApplicationController
  def index
    @users = User.all
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @like = Like.where(user_id: @user.id)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admins_users_path
  end
end

app/controllers/publics/users_controller.rb
class Publics::UsersController < Publics::ApplicationController
  def index
    @user = User.find(current_user.id)
    @matchings = @user.following & @user.followed
  end

  def show
    @user = User.find(params[:id])
    @like = Like.where(user_id: @user.id)
    # 相互フォロー もしくは @user がログインユーザーの場合
    if !current_user.following?(@user).nil? && !current_user.followed?(@user).nil? || @user == current_user
      # Why: blockメソッドを条件分岐で利用するために必須
      if @user != current_user
        # フォローしているユーザー(@user)をブロックしていた場合
        redirect_to user_path(current_user) if current_user.following?(@user).block == true
        # DM機能
        @room_id = (@user.entries.pluck(:room_id) & current_user.entries.pluck(:room_id)).first
        unless @room_id
          @room = Room.new
          @entry = Entry.new
        end
      end
    else
      redirect_to user_path(current_user)
    end
  end

  def matching
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) if @user.id != current_user.id
    # ログインユーザーの住所情報取得
    @area = current_user.prefecture
    # ログインユーザーの好きなゲーム種類の取得
    @games = current_user.gamegenre_ids
    # ユーザーモデルに<好きなゲーム種類テーブル>と<マッチングテーブル>を追加
    @all_user = User.joins(:likes).left_outer_joins(:following_relationships)
    # ログインユーザー情報の除外と、ログインユーザーの好きなゲーム種類で絞り込み
    @matching = @all_user.where.not(id: current_user.id).where(prefecture: @area).where(likes: { gamegenre_id: @games }).uniq.sample(8)
  end

  def info
    @id = params[:user_id]
    @user = User.find(@id)
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) if @user.id != current_user.id
  end

  def edit2
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless current_user
  end

  def update
    @user = User.find(params[:id])
    @like = Like.where(user_id: @user.id)
    if @user.update(user_params)
      respond_to do |format|
        format.html
        format.js
        format.json
      end
    else
      render :edit
    end
  end

  def destroy
    user = current_user
    user.destroy
    redirect_to root_path
  end

  def block; end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :first_name_kana,
                                 :last_name_kana, :nickname, :prefecture,
                                 :active_area, :active_time, :active_content,
                                 :game_name, :introduction, :image_profile_id,
                                 :email, gamegenre_ids: [])
  end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/publics/users_helper.rb
module Publics::UsersHelper
end

app/views/admins/users/destroy.html.erb
<h1>Admins::Users#destroy</h1>
<p>Find me in app/views/admins/users/destroy.html.erb</p>

app/views/admins/users/index.html.erb
<div class="container">
	<div class="row admin_user_body" id="body">
		<div class="header">
			<h3>　All User</h3>
		</div>
	    <% flash.each do |name, msg| %>
	      <div class="alert alert-<%= name %>">
	        <%= msg %>
	      </div>
	    <% end %>
		<div class="user_all">
			<table class="table table-bordered table-hover">
				<thead>
					<tr>
						<td>User Id</td>
						<td>Nick Name</td>
						<td>Full Name</td>
						<td>Email</td>
					</tr>
				</thead>
				<% @users.each do |f| %>
				<tbody>
					<tr>
						<td><%= f.id %></td>
						<td><%= link_to "#{f.nickname}", admins_user_path(f.id) %></td>
						<td><%= f.first_name %><%= f.last_name %>(<%= f.first_name_kana %><%= f.last_name_kana %>)</td>
						<td><%= f.email %></td>
					</tr>
				</tbody>
				<% end %>
			</table>
			<%= paginate @users %>
		</div>
	</div>
</div>

app/views/admins/users/show.html.erb
<div class="container">
	<div class="row"  id="body">
		<div class="header">
			<h3>　User Info</h3>
		</div>
		<div class="window-top" id="top">
			<div class="left_profile">
				<table class="image_table">
					<tbody>
						<tr>
							<td>
								<div class="image_profile">
									<img src="<%=@user.image_profile_id %>" , id="image_profile", width="180">
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="right_profile">
				<table class="table table-sm info_table">
					<tbody>
						<tr>
							<th><span>ニックネーム</span></th>
							<td><%= @user.nickname %></td>
						</tr>
						<tr>
							<th><span>住まい</span></th>
							<td><%= @user.prefecture %></td>
						</tr>
						<tr>
							<th><span>主な活動範囲</span></th>
							<td><%= @user.active_area %></td>
						</tr>
						<tr>
							<th><span>主な活動時間</span></th>
							<td><%= @user.active_time %></td>
						</tr>
						<tr>
							<th><span>傾向</span></th>
							<td><%= @user.active_content %></td>
						</tr>
						<tr>
							<th><span>フルネーム</span></th>
							<td><%= "#{@user.first_name}#{@user.last_name}" %></td>
						</tr>
						<tr>
							<th><span>メールアドレス</span></th>
							<td><%= @user.email %></td>
						</tr>
						<tr>
							<th><span>生年月日</span></th>
							<td><%= @user.birthday.strftime("%Y/%m/%d") %></td>
						</tr>
					</tbody>
				</table>
			</div>

		</div>
		<div class="window-bottom" id="bottom">
			<div id='calendar'>
			</div>
			<div class="user_info">
				<span>　自己紹介</span>
				<div class="info_box overflow-auto">
					<%= simple_format(@user.introduction) %>
				</div>
				<span>　好きなゲームのジャンル</span>
				<div class="info_box">
					<% @like.each do |f| %>
						<%= f.gamegenre.gamegenre %><span>/</span>
					<% end %>
				</div>
				<span>　好きなゲーム</span>
				<div class="info_box overflow-auto">
					<%= simple_format(@user.game_name) %>
				</div>
			</div>
			<div id="user-events" data-event-id="<%= @user.events.to_json %>"></div>
		</div>
		<div class="user_delete">
			<%= link_to "退会させる", admins_user_path(@user), method: :delete, "data-confirm" => "本当に退会させますか?", class:"btn btn-outline-dark" %>
		</div>
	</div>
</div>

<script>
	$(function () {
		$(document).ready(function(){
			var userEvents = $('#user-events').data('event-id');
		    var calendar = $('#calendar').fullCalendar({
		        events: userEvents,
		        eventLimit: true,
		        selectable: true,
		        selectHelper: true,
		        ignoreTimezone: false,
		        // select: select,
		        eventClick: function(event) {
		        	alert('ゲーム名:' + '\n' + event.title + '\n内容:'+ '\n' + event.description + '\n開始時間:' + '\n' + event.start.format('YYYY年MM月DD日 HH:mm') + '\n終了時間:' + '\n' + event.end.format('YYYY年MM月DD日 HH:mm'));
		        },
			    header: {
			      left: 'prev,next today',
			      center: 'title',
			      right: 'month,agendaDay'
			    },
		    });
		});
	});
</script>